"""new fields in user model

Revision ID: 064a4cb959d0
Revises: 3aeba6b8ab05
Create Date: 2021-05-22 18:27:39.548732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064a4cb959d0'
down_revision = '3aeba6b8ab05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
